// Generated by docs/make-run-script.py from docs/shots/hero.txt — do not edit.
//
// Every line below was printed by `nightaudit watch` during a real code_review
// of this repository. Editing this file by hand is how the landing page last
// ended up advertising output no command has ever produced; edit the capture
// and regenerate, or change the CLI and recapture. CI fails on a diff.

import type { ScriptLine } from "@/lib/run-script";

export const RUN_SCRIPT: readonly ScriptLine[] = [
  { kind: "banner", msg: "nightaudit · watching for runs — ctrl-c to stop", used: 0 },
  { kind: "meta", msg: "┌ nightaudit · code_review", detail: "claude_code · 15:23:27", used: 0 },
  { kind: "start", msg: "⏺ ~/projects/nightaudit", used: 0 },
  { kind: "prose", msg: "I'll start by exploring the repository structure to understand what I'm reviewing.", used: 0 },
  { kind: "tool", msg: "⏺ Glob", detail: "(pattern: **/*)", used: 0 },
  { kind: "result", msg: "⎿  .git/info/exclude (+100 lines)", used: 0 },
  { kind: "thinking", msg: "✻ thinking", used: 0 },
  { kind: "prose", msg: "The repo is a Python CLI called `nightaudit`. Let me read the source files, skipping", used: 0 },
  { kind: "prose", msg: "the vendored `.venv`.", used: 0 },
  { kind: "elide", msg: "54 lines", used: 0 },
  { kind: "high", msg: "🔴 HIGH nightaudit/adapters/claude_code.py · 267", detail: "— Replace the buffered `subprocess.…", used: 0 },
  { kind: "med", msg: "🟠 MED  nightaudit/lock.py · 121", detail: "— Have `release()` re-read the lockfile and unlink …", used: 0 },
  { kind: "low", msg: "🟡 LOW  nightaudit/cron.py · 27", detail: "— Shell-quote the interpreter path (`shlex.quote`) i…", used: 0 },
  { kind: "end", msg: "└ ✓ ok", detail: "2m18s · 7 findings", used: 1 },
] as const;
